### ISSUE TITLE
Migrate View "slot_by_holders" into saved configuration

### ISSUE THREAD

**Issue by torenware** [badcamp/badcamp-2018#196]
I've created a tracking view ID="slot_by_holders", which lists what sessions and events are assigned to what venues and time slots. This was used to make sure I was not double-assigning to the same room during the same timeslot.

The view is currently implemented in production, to be moved when it's convenient for the Wizards to deal with it.

Filename: views.view.slot_by_holders.yml 

```yaml
uuid: 3663daf9-0281-449e-b41e-f83bd9749336
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_timeslot
    - field.storage.node.field_venue
    - node.type.event
    - node.type.session
    - user.role.administrator
    - user.role.event_manager
    - user.role.session_manager
  module:
    - node
    - taxonomy
    - user
id: slot_by_holders
label: 'Slot By Holders'
module: views
description: 'TRACKING VIEW to prevent double assignment of events/sessions to venues.'
tag: ''
base_table: node_field_data
base_field: nid
core: 8.x
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: 0
    display_options:
      access:
        type: role
        options:
          role:
            event_manager: event_manager
            session_manager: session_manager
            administrator: administrator
      cache:
        type: tag
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: false
          distinct: false
          replica: false
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: some
        options:
          items_per_page: 100
          offset: 0
      style:
        type: table
      row:
        type: fields
      fields:
        field_venue:
          id: field_venue
          table: node__field_venue
          field: field_venue
          relationship: none
          group_type: group
          admin_label: ''
          label: Venue
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: target_id
          type: entity_reference_label
          settings:
            link: true
          group_column: target_id
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          plugin_id: field
        name:
          id: name
          table: taxonomy_term_field_data
          field: name
          relationship: parent
          group_type: group
          admin_label: ''
          label: Date
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: string
          settings:
            link_to_entity: true
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          convert_spaces: false
          entity_type: taxonomy_term
          entity_field: name
          plugin_id: term_name
        field_timeslot:
          id: field_timeslot
          table: node__field_timeslot
          field: field_timeslot
          relationship: none
          group_type: group
          admin_label: ''
          label: Timeslot
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: target_id
          type: entity_reference_label
          settings:
            link: true
          group_column: target_id
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          plugin_id: field
        title:
          id: title
          table: node_field_data
          field: title
          entity_type: node
          entity_field: title
          alter:
            alter_text: false
            make_link: false
            absolute: false
            trim: false
            word_boundary: false
            ellipsis: false
            strip_tags: false
            html: false
          hide_empty: false
          empty_zero: false
          settings:
            link_to_entity: true
          plugin_id: field
          relationship: none
          group_type: group
          admin_label: ''
          label: Title
          exclude: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_alter_empty: true
          click_sort_column: value
          type: string
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
      filters:
        status:
          value: '1'
          table: node_field_data
          field: status
          plugin_id: boolean
          entity_type: node
          entity_field: status
          id: status
          expose:
            operator: ''
          group: 1
        type:
          id: type
          table: node_field_data
          field: type
          relationship: none
          group_type: group
          admin_label: 'Venued Content'
          operator: in
          value:
            event: event
            session: session
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          entity_type: node
          entity_field: type
          plugin_id: bundle
      sorts:
        field_venue_target_id:
          id: field_venue_target_id
          table: node__field_venue
          field: field_venue_target_id
          relationship: none
          group_type: group
          admin_label: ''
          order: ASC
          exposed: false
          expose:
            label: ''
          plugin_id: standard
        weight_1:
          id: weight_1
          table: taxonomy_term_field_data
          field: weight
          relationship: parent
          group_type: group
          admin_label: 'Date Order'
          order: ASC
          exposed: false
          expose:
            label: ''
          entity_type: taxonomy_term
          entity_field: weight
          plugin_id: standard
        weight:
          id: weight
          table: taxonomy_term_field_data
          field: weight
          relationship: field_timeslot
          group_type: group
          admin_label: 'Time Order'
          order: ASC
          exposed: false
          expose:
            label: ''
          entity_type: taxonomy_term
          entity_field: weight
          plugin_id: standard
      title: 'Slot By Holders'
      header: {  }
      footer: {  }
      empty: {  }
      relationships:
        field_timeslot:
          id: field_timeslot
          table: node__field_timeslot
          field: field_timeslot
          relationship: none
          group_type: group
          admin_label: 'field_timeslot: Taxonomy term'
          required: true
          plugin_id: standard
        field_venue:
          id: field_venue
          table: node__field_venue
          field: field_venue
          relationship: none
          group_type: group
          admin_label: 'field_venue: Taxonomy term'
          required: true
          plugin_id: standard
        parent:
          id: parent
          table: taxonomy_term_hierarchy
          field: parent
          relationship: field_timeslot
          group_type: group
          admin_label: Date
          required: true
          plugin_id: standard
      arguments: {  }
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - 'user.node_grants:view'
        - user.roles
      tags:
        - 'config:field.storage.node.field_timeslot'
        - 'config:field.storage.node.field_venue'
        - extensions
  page_1:
    display_plugin: page
    id: page_1
    display_title: Page
    position: 1
    display_options:
      display_extenders: {  }
      path: slot-by-holders
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - 'user.node_grants:view'
        - user.roles
      tags:
        - 'config:field.storage.node.field_timeslot'
        - 'config:field.storage.node.field_venue'
        - extensions

```
